// Mocks generated by Mockito 5.4.6 from annotations
// in audiflow_domain/test/features/feed/services/feed_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:audiflow_core/audiflow_core.dart' as _i20;
import 'package:audiflow_domain/src/features/feed/builders/podcast_builder.dart'
    as _i3;
import 'package:audiflow_domain/src/features/feed/models/episode.dart' as _i13;
import 'package:audiflow_domain/src/features/feed/models/feed_parse_progress.dart'
    as _i17;
import 'package:audiflow_domain/src/features/feed/models/numbering_extractor.dart'
    as _i15;
import 'package:audiflow_domain/src/features/feed/models/pattern_summary.dart'
    as _i25;
import 'package:audiflow_domain/src/features/feed/models/root_meta.dart'
    as _i23;
import 'package:audiflow_domain/src/features/feed/models/smart_playlist_pattern_config.dart'
    as _i16;
import 'package:audiflow_domain/src/features/feed/repositories/episode_repository.dart'
    as _i12;
import 'package:audiflow_domain/src/features/feed/repositories/smart_playlist_config_repository.dart'
    as _i22;
import 'package:audiflow_domain/src/features/feed/services/feed_parser_service.dart'
    as _i21;
import 'package:audiflow_domain/src/features/settings/repositories/app_settings_repository.dart'
    as _i18;
import 'package:audiflow_domain/src/features/station/models/station_podcast.dart'
    as _i27;
import 'package:audiflow_domain/src/features/station/repositories/station_podcast_repository.dart'
    as _i26;
import 'package:audiflow_domain/src/features/subscription/models/subscriptions.dart'
    as _i2;
import 'package:audiflow_domain/src/features/subscription/repositories/subscription_repository.dart'
    as _i10;
import 'package:audiflow_podcast/audiflow_podcast.dart' as _i14;
import 'package:dio/src/adapter.dart' as _i6;
import 'package:dio/src/cancel_token.dart' as _i28;
import 'package:dio/src/dio.dart' as _i9;
import 'package:dio/src/dio_mixin.dart' as _i5;
import 'package:dio/src/options.dart' as _i4;
import 'package:dio/src/response.dart' as _i8;
import 'package:dio/src/transformer.dart' as _i7;
import 'package:flutter/material.dart' as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i24;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSubscription_0 extends _i1.SmartFake implements _i2.Subscription {
  _FakeSubscription_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeParsedFeed_1 extends _i1.SmartFake implements _i3.ParsedFeed {
  _FakeParsedFeed_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_2 extends _i1.SmartFake implements _i4.BaseOptions {
  _FakeBaseOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_3 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_4 extends _i1.SmartFake
    implements _i6.HttpClientAdapter {
  _FakeHttpClientAdapter_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_5 extends _i1.SmartFake implements _i7.Transformer {
  _FakeTransformer_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_6<T1> extends _i1.SmartFake implements _i8.Response<T1> {
  _FakeResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_7 extends _i1.SmartFake implements _i9.Dio {
  _FakeDio_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i10.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.Subscription> subscribe({
    required String? itunesId,
    required String? feedUrl,
    required String? title,
    required String? artistName,
    String? artworkUrl,
    String? description,
    List<String>? genres,
    bool? explicit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {
              #itunesId: itunesId,
              #feedUrl: feedUrl,
              #title: title,
              #artistName: artistName,
              #artworkUrl: artworkUrl,
              #description: description,
              #genres: genres,
              #explicit: explicit,
            }),
            returnValue: _i11.Future<_i2.Subscription>.value(
              _FakeSubscription_0(
                this,
                Invocation.method(#subscribe, [], {
                  #itunesId: itunesId,
                  #feedUrl: feedUrl,
                  #title: title,
                  #artistName: artistName,
                  #artworkUrl: artworkUrl,
                  #description: description,
                  #genres: genres,
                  #explicit: explicit,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Subscription>);

  @override
  _i11.Future<void> unsubscribe(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [itunesId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> isSubscribed(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribed, [itunesId]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> isSubscribedByFeedUrl(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribedByFeedUrl, [feedUrl]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<List<_i2.Subscription>> getSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptions, []),
            returnValue: _i11.Future<List<_i2.Subscription>>.value(
              <_i2.Subscription>[],
            ),
          )
          as _i11.Future<List<_i2.Subscription>>);

  @override
  _i11.Stream<List<_i2.Subscription>> watchSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#watchSubscriptions, []),
            returnValue: _i11.Stream<List<_i2.Subscription>>.empty(),
          )
          as _i11.Stream<List<_i2.Subscription>>);

  @override
  _i11.Future<_i2.Subscription?> getSubscription(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscription, [itunesId]),
            returnValue: _i11.Future<_i2.Subscription?>.value(),
          )
          as _i11.Future<_i2.Subscription?>);

  @override
  _i11.Future<_i2.Subscription?> getByFeedUrl(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getByFeedUrl, [feedUrl]),
            returnValue: _i11.Future<_i2.Subscription?>.value(),
          )
          as _i11.Future<_i2.Subscription?>);

  @override
  _i11.Future<_i2.Subscription?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i2.Subscription?>.value(),
          )
          as _i11.Future<_i2.Subscription?>);

  @override
  _i11.Future<void> updateLastRefreshed(
    String? itunesId,
    DateTime? timestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastRefreshed, [itunesId, timestamp]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i2.Subscription> getOrCreateCached({
    required String? itunesId,
    required String? feedUrl,
    required String? title,
    required String? artistName,
    String? artworkUrl,
    String? description,
    List<String>? genres,
    bool? explicit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateCached, [], {
              #itunesId: itunesId,
              #feedUrl: feedUrl,
              #title: title,
              #artistName: artistName,
              #artworkUrl: artworkUrl,
              #description: description,
              #genres: genres,
              #explicit: explicit,
            }),
            returnValue: _i11.Future<_i2.Subscription>.value(
              _FakeSubscription_0(
                this,
                Invocation.method(#getOrCreateCached, [], {
                  #itunesId: itunesId,
                  #feedUrl: feedUrl,
                  #title: title,
                  #artistName: artistName,
                  #artworkUrl: artworkUrl,
                  #description: description,
                  #genres: genres,
                  #explicit: explicit,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Subscription>);

  @override
  _i11.Future<_i2.Subscription?> promoteToSubscribed(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#promoteToSubscribed, [itunesId]),
            returnValue: _i11.Future<_i2.Subscription?>.value(),
          )
          as _i11.Future<_i2.Subscription?>);

  @override
  _i11.Future<void> updateLastAccessed(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastAccessed, [id]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i2.Subscription>> getCachedSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSubscriptions, []),
            returnValue: _i11.Future<List<_i2.Subscription>>.value(
              <_i2.Subscription>[],
            ),
          )
          as _i11.Future<List<_i2.Subscription>>);

  @override
  _i11.Future<bool> deleteById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [id]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> updateAutoDownload(
    int? id, {
    required bool? autoDownload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateAutoDownload,
              [id],
              {#autoDownload: autoDownload},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> updateHttpCacheHeaders(
    int? id, {
    String? etag,
    String? lastModified,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateHttpCacheHeaders,
              [id],
              {#etag: etag, #lastModified: lastModified},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> clearAllHttpCacheHeaders() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllHttpCacheHeaders, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [EpisodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpisodeRepository extends _i1.Mock implements _i12.EpisodeRepository {
  MockEpisodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i13.Episode>> getByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getByPodcastId, [podcastId]),
            returnValue: _i11.Future<List<_i13.Episode>>.value(
              <_i13.Episode>[],
            ),
          )
          as _i11.Future<List<_i13.Episode>>);

  @override
  _i11.Stream<List<_i13.Episode>> watchByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#watchByPodcastId, [podcastId]),
            returnValue: _i11.Stream<List<_i13.Episode>>.empty(),
          )
          as _i11.Stream<List<_i13.Episode>>);

  @override
  _i11.Future<_i13.Episode?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i13.Episode?>.value(),
          )
          as _i11.Future<_i13.Episode?>);

  @override
  _i11.Future<_i13.Episode?> getByAudioUrl(String? audioUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getByAudioUrl, [audioUrl]),
            returnValue: _i11.Future<_i13.Episode?>.value(),
          )
          as _i11.Future<_i13.Episode?>);

  @override
  _i11.Future<_i13.Episode?> getByPodcastIdAndGuid(
    int? podcastId,
    String? guid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByPodcastIdAndGuid, [podcastId, guid]),
            returnValue: _i11.Future<_i13.Episode?>.value(),
          )
          as _i11.Future<_i13.Episode?>);

  @override
  _i11.Future<void> upsertEpisodes(List<_i13.Episode>? episodes) =>
      (super.noSuchMethod(
            Invocation.method(#upsertEpisodes, [episodes]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> upsertFromFeedItems(
    int? podcastId,
    List<_i14.PodcastItem>? items, {
    _i15.NumberingExtractor? extractor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertFromFeedItems,
              [podcastId, items],
              {#extractor: extractor},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> upsertFromFeedItemsWithConfig(
    int? podcastId,
    List<_i14.PodcastItem>? items, {
    required _i16.SmartPlaylistPatternConfig? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertFromFeedItemsWithConfig,
              [podcastId, items],
              {#config: config},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i13.Episode>> getByIds(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getByIds, [ids]),
            returnValue: _i11.Future<List<_i13.Episode>>.value(
              <_i13.Episode>[],
            ),
          )
          as _i11.Future<List<_i13.Episode>>);

  @override
  _i11.Future<Set<String>> getGuidsByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getGuidsByPodcastId, [podcastId]),
            returnValue: _i11.Future<Set<String>>.value(<String>{}),
          )
          as _i11.Future<Set<String>>);

  @override
  _i11.Future<_i13.Episode?> getNewestByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getNewestByPodcastId, [podcastId]),
            returnValue: _i11.Future<_i13.Episode?>.value(),
          )
          as _i11.Future<_i13.Episode?>);

  @override
  _i11.Future<void> storeTranscriptAndChapterDataFromParsed(
    int? podcastId,
    List<_i17.ParsedEpisodeMediaMeta>? mediaMetas,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeTranscriptAndChapterDataFromParsed, [
              podcastId,
              mediaMetas,
            ]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<int> deleteByPodcastIdAndGuids(
    int? podcastId,
    Set<String>? guids, {
    Set<String>? protectedGuids = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteByPodcastIdAndGuids,
              [podcastId, guids],
              {#protectedGuids: protectedGuids},
            ),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<_i13.Episode>> getSubsequentEpisodes({
    required int? podcastId,
    required int? afterEpisodeNumber,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSubsequentEpisodes, [], {
              #podcastId: podcastId,
              #afterEpisodeNumber: afterEpisodeNumber,
              #limit: limit,
            }),
            returnValue: _i11.Future<List<_i13.Episode>>.value(
              <_i13.Episode>[],
            ),
          )
          as _i11.Future<List<_i13.Episode>>);
}

/// A class which mocks [AppSettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSettingsRepository extends _i1.Mock
    implements _i18.AppSettingsRepository {
  MockAppSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.ThemeMode getThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, []),
            returnValue: _i19.ThemeMode.system,
          )
          as _i19.ThemeMode);

  @override
  _i11.Future<void> setThemeMode(_i19.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [mode]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setLocale(String? locale) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [locale]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  double getTextScale() =>
      (super.noSuchMethod(
            Invocation.method(#getTextScale, []),
            returnValue: 0.0,
          )
          as double);

  @override
  _i11.Future<void> setTextScale(double? scale) =>
      (super.noSuchMethod(
            Invocation.method(#setTextScale, [scale]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  double getPlaybackSpeed() =>
      (super.noSuchMethod(
            Invocation.method(#getPlaybackSpeed, []),
            returnValue: 0.0,
          )
          as double);

  @override
  _i11.Future<void> setPlaybackSpeed(double? speed) =>
      (super.noSuchMethod(
            Invocation.method(#setPlaybackSpeed, [speed]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  int getSkipForwardSeconds() =>
      (super.noSuchMethod(
            Invocation.method(#getSkipForwardSeconds, []),
            returnValue: 0,
          )
          as int);

  @override
  _i11.Future<void> setSkipForwardSeconds(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#setSkipForwardSeconds, [seconds]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  int getSkipBackwardSeconds() =>
      (super.noSuchMethod(
            Invocation.method(#getSkipBackwardSeconds, []),
            returnValue: 0,
          )
          as int);

  @override
  _i11.Future<void> setSkipBackwardSeconds(int? seconds) =>
      (super.noSuchMethod(
            Invocation.method(#setSkipBackwardSeconds, [seconds]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  double getAutoCompleteThreshold() =>
      (super.noSuchMethod(
            Invocation.method(#getAutoCompleteThreshold, []),
            returnValue: 0.0,
          )
          as double);

  @override
  _i11.Future<void> setAutoCompleteThreshold(double? threshold) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoCompleteThreshold, [threshold]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool getContinuousPlayback() =>
      (super.noSuchMethod(
            Invocation.method(#getContinuousPlayback, []),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<void> setContinuousPlayback(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setContinuousPlayback, [enabled]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i20.AutoPlayOrder getAutoPlayOrder() =>
      (super.noSuchMethod(
            Invocation.method(#getAutoPlayOrder, []),
            returnValue: _i20.AutoPlayOrder.defaultOrder,
          )
          as _i20.AutoPlayOrder);

  @override
  _i11.Future<void> setAutoPlayOrder(_i20.AutoPlayOrder? order) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoPlayOrder, [order]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i20.DuckInterruptionBehavior getDuckInterruptionBehavior() =>
      (super.noSuchMethod(
            Invocation.method(#getDuckInterruptionBehavior, []),
            returnValue: _i20.DuckInterruptionBehavior.duck,
          )
          as _i20.DuckInterruptionBehavior);

  @override
  _i11.Future<void> setDuckInterruptionBehavior(
    _i20.DuckInterruptionBehavior? behavior,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDuckInterruptionBehavior, [behavior]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool getWifiOnlyDownload() =>
      (super.noSuchMethod(
            Invocation.method(#getWifiOnlyDownload, []),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<void> setWifiOnlyDownload(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setWifiOnlyDownload, [enabled]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool getAutoDeletePlayed() =>
      (super.noSuchMethod(
            Invocation.method(#getAutoDeletePlayed, []),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<void> setAutoDeletePlayed(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoDeletePlayed, [enabled]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  int getMaxConcurrentDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#getMaxConcurrentDownloads, []),
            returnValue: 0,
          )
          as int);

  @override
  _i11.Future<void> setMaxConcurrentDownloads(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#setMaxConcurrentDownloads, [count]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  int getBatchDownloadLimit() =>
      (super.noSuchMethod(
            Invocation.method(#getBatchDownloadLimit, []),
            returnValue: 0,
          )
          as int);

  @override
  _i11.Future<void> setBatchDownloadLimit(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#setBatchDownloadLimit, [limit]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool getAutoSync() =>
      (super.noSuchMethod(
            Invocation.method(#getAutoSync, []),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<void> setAutoSync(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoSync, [enabled]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  int getSyncIntervalMinutes() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncIntervalMinutes, []),
            returnValue: 0,
          )
          as int);

  @override
  _i11.Future<void> setSyncIntervalMinutes(int? minutes) =>
      (super.noSuchMethod(
            Invocation.method(#setSyncIntervalMinutes, [minutes]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool getWifiOnlySync() =>
      (super.noSuchMethod(
            Invocation.method(#getWifiOnlySync, []),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<void> setWifiOnlySync(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setWifiOnlySync, [enabled]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool getNotifyNewEpisodes() =>
      (super.noSuchMethod(
            Invocation.method(#getNotifyNewEpisodes, []),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<void> setNotifyNewEpisodes(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setNotifyNewEpisodes, [enabled]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setSearchCountry(String? country) =>
      (super.noSuchMethod(
            Invocation.method(#setSearchCountry, [country]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  int getLastTabIndex() =>
      (super.noSuchMethod(
            Invocation.method(#getLastTabIndex, []),
            returnValue: 0,
          )
          as int);

  @override
  _i11.Future<void> setLastTabIndex(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#setLastTabIndex, [index]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  bool getVoiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getVoiceEnabled, []),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Future<void> setVoiceEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setVoiceEnabled, [enabled]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [FeedParserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedParserService extends _i1.Mock implements _i21.FeedParserService {
  MockFeedParserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i3.ParsedFeed> parseFromUrl(
    String? url, {
    _i14.CacheOptions? cacheOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #parseFromUrl,
              [url],
              {#cacheOptions: cacheOptions},
            ),
            returnValue: _i11.Future<_i3.ParsedFeed>.value(
              _FakeParsedFeed_1(
                this,
                Invocation.method(
                  #parseFromUrl,
                  [url],
                  {#cacheOptions: cacheOptions},
                ),
              ),
            ),
          )
          as _i11.Future<_i3.ParsedFeed>);

  @override
  _i11.Future<_i3.ParsedFeed> parseFromString(
    String? xmlContent, {
    DateTime? knownNewestPubDate,
    String? knownNewestGuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #parseFromString,
              [xmlContent],
              {
                #knownNewestPubDate: knownNewestPubDate,
                #knownNewestGuid: knownNewestGuid,
              },
            ),
            returnValue: _i11.Future<_i3.ParsedFeed>.value(
              _FakeParsedFeed_1(
                this,
                Invocation.method(
                  #parseFromString,
                  [xmlContent],
                  {
                    #knownNewestPubDate: knownNewestPubDate,
                    #knownNewestGuid: knownNewestGuid,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i3.ParsedFeed>);

  @override
  _i11.Stream<_i17.FeedParseProgress> parseWithProgress({
    required String? xmlContent,
    required int? podcastId,
    required Set<String>? knownGuids,
    required _i11.Future<void> Function(
      List<_i13.Episode>,
      List<_i17.ParsedEpisodeMediaMeta>,
    )?
    onBatchReady,
    int? batchSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#parseWithProgress, [], {
              #xmlContent: xmlContent,
              #podcastId: podcastId,
              #knownGuids: knownGuids,
              #onBatchReady: onBatchReady,
              #batchSize: batchSize,
            }),
            returnValue: _i11.Stream<_i17.FeedParseProgress>.empty(),
          )
          as _i11.Stream<_i17.FeedParseProgress>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SmartPlaylistConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmartPlaylistConfigRepository extends _i1.Mock
    implements _i22.SmartPlaylistConfigRepository {
  MockSmartPlaylistConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i23.RootMeta> fetchRootMeta() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRootMeta, []),
            returnValue: _i11.Future<_i23.RootMeta>.value(
              _i24.dummyValue<_i23.RootMeta>(
                this,
                Invocation.method(#fetchRootMeta, []),
              ),
            ),
          )
          as _i11.Future<_i23.RootMeta>);

  @override
  _i11.Future<_i16.SmartPlaylistPatternConfig> getConfig(
    _i25.PatternSummary? summary,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, [summary]),
            returnValue: _i11.Future<_i16.SmartPlaylistPatternConfig>.value(
              _i24.dummyValue<_i16.SmartPlaylistPatternConfig>(
                this,
                Invocation.method(#getConfig, [summary]),
              ),
            ),
          )
          as _i11.Future<_i16.SmartPlaylistPatternConfig>);

  @override
  _i25.PatternSummary? findMatchingPattern(
    String? podcastGuid,
    String? feedUrl,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findMatchingPattern, [podcastGuid, feedUrl]),
          )
          as _i25.PatternSummary?);

  @override
  _i11.Future<void> reconcileCache(List<_i25.PatternSummary>? latest) =>
      (super.noSuchMethod(
            Invocation.method(#reconcileCache, [latest]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void setPatternSummaries(List<_i25.PatternSummary>? summaries) =>
      super.noSuchMethod(
        Invocation.method(#setPatternSummaries, [summaries]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StationPodcastRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStationPodcastRepository extends _i1.Mock
    implements _i26.StationPodcastRepository {
  MockStationPodcastRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<List<_i27.StationPodcast>> getByStation(int? stationId) =>
      (super.noSuchMethod(
            Invocation.method(#getByStation, [stationId]),
            returnValue: _i11.Future<List<_i27.StationPodcast>>.value(
              <_i27.StationPodcast>[],
            ),
          )
          as _i11.Future<List<_i27.StationPodcast>>);

  @override
  _i11.Stream<List<_i27.StationPodcast>> watchByStation(int? stationId) =>
      (super.noSuchMethod(
            Invocation.method(#watchByStation, [stationId]),
            returnValue: _i11.Stream<List<_i27.StationPodcast>>.empty(),
          )
          as _i11.Stream<List<_i27.StationPodcast>>);

  @override
  _i11.Future<void> add(
    int? stationId,
    int? podcastId, {
    int? sortOrder = 0,
    int? episodeLimit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #add,
              [stationId, podcastId],
              {#sortOrder: sortOrder, #episodeLimit: episodeLimit},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> update(_i27.StationPodcast? stationPodcast) =>
      (super.noSuchMethod(
            Invocation.method(#update, [stationPodcast]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> remove(int? stationId, int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [stationId, podcastId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> removeAllForStation(int? stationId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAllForStation, [stationId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i9.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_2(this, Invocation.getter(#options)),
          )
          as _i4.BaseOptions);

  @override
  _i5.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_3(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i5.Interceptors);

  @override
  _i6.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_4(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i6.HttpClientAdapter);

  @override
  _i7.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_5(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i7.Transformer);

  @override
  set options(_i4.BaseOptions? value) => super.noSuchMethod(
    Invocation.setter(#options, value),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i6.HttpClientAdapter? value) => super.noSuchMethod(
    Invocation.setter(#httpClientAdapter, value),
    returnValueForMissingStub: null,
  );

  @override
  set transformer(_i7.Transformer? value) => super.noSuchMethod(
    Invocation.setter(#transformer, value),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i8.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i4.Options? options,
    _i28.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i4.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i28.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i4.FileAccessMode? fileAccessMode = _i4.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i11.Future<_i8.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<dynamic>>);

  @override
  _i11.Future<_i8.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i4.ProgressCallback? onReceiveProgress,
    _i28.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i4.FileAccessMode? fileAccessMode = _i4.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i4.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i11.Future<_i8.Response<dynamic>>.value(
              _FakeResponse_6<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<dynamic>>);

  @override
  _i11.Future<_i8.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i28.CancelToken? cancelToken,
    _i4.Options? options,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i28.CancelToken? cancelToken,
    _i4.Options? options,
    _i4.ProgressCallback? onSendProgress,
    _i4.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i11.Future<_i8.Response<T>> fetch<T>(_i4.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i11.Future<_i8.Response<T>>.value(
              _FakeResponse_6<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i11.Future<_i8.Response<T>>);

  @override
  _i9.Dio clone({
    _i4.BaseOptions? options,
    _i5.Interceptors? interceptors,
    _i6.HttpClientAdapter? httpClientAdapter,
    _i7.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_7(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i9.Dio);
}
