// Mocks generated by Mockito 5.4.6 from annotations
// in audiflow_domain/test/features/download/services/download_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:audiflow_domain/src/features/download/models/download_status.dart'
    as _i6;
import 'package:audiflow_domain/src/features/download/models/download_task.dart'
    as _i5;
import 'package:audiflow_domain/src/features/download/repositories/download_repository.dart'
    as _i3;
import 'package:audiflow_domain/src/features/download/services/download_file_service.dart'
    as _i8;
import 'package:audiflow_domain/src/features/download/services/download_queue_service.dart'
    as _i7;
import 'package:audiflow_domain/src/features/feed/models/episode.dart' as _i11;
import 'package:audiflow_domain/src/features/feed/models/feed_parse_progress.dart'
    as _i15;
import 'package:audiflow_domain/src/features/feed/models/numbering_extractor.dart'
    as _i13;
import 'package:audiflow_domain/src/features/feed/models/preset_config.dart'
    as _i14;
import 'package:audiflow_domain/src/features/feed/repositories/episode_repository.dart'
    as _i10;
import 'package:audiflow_domain/src/features/monitoring/models/analytics_event.dart'
    as _i17;
import 'package:audiflow_domain/src/features/subscription/models/subscriptions.dart'
    as _i2;
import 'package:audiflow_domain/src/features/subscription/repositories/subscription_repository.dart'
    as _i16;
import 'package:audiflow_podcast/audiflow_podcast.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSubscription_0 extends _i1.SmartFake implements _i2.Subscription {
  _FakeSubscription_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DownloadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadRepository extends _i1.Mock
    implements _i3.DownloadRepository {
  MockDownloadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.DownloadTask?> createDownload({
    required int? episodeId,
    required String? audioUrl,
    required bool? wifiOnly,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDownload, [], {
              #episodeId: episodeId,
              #audioUrl: audioUrl,
              #wifiOnly: wifiOnly,
            }),
            returnValue: _i4.Future<_i5.DownloadTask?>.value(),
          )
          as _i4.Future<_i5.DownloadTask?>);

  @override
  _i4.Future<_i5.DownloadTask?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i5.DownloadTask?>.value(),
          )
          as _i4.Future<_i5.DownloadTask?>);

  @override
  _i4.Future<_i5.DownloadTask?> getByEpisodeId(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getByEpisodeId, [episodeId]),
            returnValue: _i4.Future<_i5.DownloadTask?>.value(),
          )
          as _i4.Future<_i5.DownloadTask?>);

  @override
  _i4.Stream<_i5.DownloadTask?> watchByEpisodeId(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#watchByEpisodeId, [episodeId]),
            returnValue: _i4.Stream<_i5.DownloadTask?>.empty(),
          )
          as _i4.Stream<_i5.DownloadTask?>);

  @override
  _i4.Future<List<_i5.DownloadTask>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i4.Future<List<_i5.DownloadTask>>.value(
              <_i5.DownloadTask>[],
            ),
          )
          as _i4.Future<List<_i5.DownloadTask>>);

  @override
  _i4.Stream<List<_i5.DownloadTask>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i4.Stream<List<_i5.DownloadTask>>.empty(),
          )
          as _i4.Stream<List<_i5.DownloadTask>>);

  @override
  _i4.Future<List<_i5.DownloadTask>> getByStatus(_i6.DownloadStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getByStatus, [status]),
            returnValue: _i4.Future<List<_i5.DownloadTask>>.value(
              <_i5.DownloadTask>[],
            ),
          )
          as _i4.Future<List<_i5.DownloadTask>>);

  @override
  _i4.Stream<List<_i5.DownloadTask>> watchByStatus(
    _i6.DownloadStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchByStatus, [status]),
            returnValue: _i4.Stream<List<_i5.DownloadTask>>.empty(),
          )
          as _i4.Stream<List<_i5.DownloadTask>>);

  @override
  _i4.Future<_i5.DownloadTask?> getCompletedForEpisode(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedForEpisode, [episodeId]),
            returnValue: _i4.Future<_i5.DownloadTask?>.value(),
          )
          as _i4.Future<_i5.DownloadTask?>);

  @override
  _i4.Future<_i5.DownloadTask?> getNextPending({required bool? isOnWifi}) =>
      (super.noSuchMethod(
            Invocation.method(#getNextPending, [], {#isOnWifi: isOnWifi}),
            returnValue: _i4.Future<_i5.DownloadTask?>.value(),
          )
          as _i4.Future<_i5.DownloadTask?>);

  @override
  _i4.Future<void> updateProgress({
    required int? id,
    required int? downloadedBytes,
    int? totalBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgress, [], {
              #id: id,
              #downloadedBytes: downloadedBytes,
              #totalBytes: totalBytes,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateStatus({
    required int? id,
    required _i6.DownloadStatus? status,
    String? localPath,
    String? lastError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [], {
              #id: id,
              #status: status,
              #localPath: localPath,
              #lastError: lastError,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> incrementRetryCount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRetryCount, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getActiveCount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getTotalStorageUsed() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalStorageUsed, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> deleteAllCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllCompleted, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [DownloadQueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadQueueService extends _i1.Mock
    implements _i7.DownloadQueueService {
  MockDownloadQueueService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.DownloadTask?> get activeDownloadStream =>
      (super.noSuchMethod(
            Invocation.getter(#activeDownloadStream),
            returnValue: _i4.Stream<_i5.DownloadTask?>.empty(),
          )
          as _i4.Stream<_i5.DownloadTask?>);

  @override
  _i4.Future<void> startQueue() =>
      (super.noSuchMethod(
            Invocation.method(#startQueue, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> pauseDownload(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseDownload, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resumeDownload(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeDownload, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelDownload(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelDownload, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> retryDownload(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#retryDownload, [taskId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DownloadFileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadFileService extends _i1.Mock
    implements _i8.DownloadFileService {
  MockDownloadFileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> downloadFile({
    required int? taskId,
    required String? url,
    required int? episodeId,
    required String? episodeTitle,
    required _i8.DownloadProgressCallback? onProgress,
    int? resumeFromBytes = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [], {
              #taskId: taskId,
              #url: url,
              #episodeId: episodeId,
              #episodeTitle: episodeTitle,
              #onProgress: onProgress,
              #resumeFromBytes: resumeFromBytes,
            }),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#downloadFile, [], {
                  #taskId: taskId,
                  #url: url,
                  #episodeId: episodeId,
                  #episodeTitle: episodeTitle,
                  #onProgress: onProgress,
                  #resumeFromBytes: resumeFromBytes,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  void cancelDownload(int? taskId) => super.noSuchMethod(
    Invocation.method(#cancelDownload, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> deleteFile(String? localPath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [localPath]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getFileSize(String? localPath) =>
      (super.noSuchMethod(
            Invocation.method(#getFileSize, [localPath]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> fileExists(String? localPath) =>
      (super.noSuchMethod(
            Invocation.method(#fileExists, [localPath]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> getDownloadsDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadsDirectory, []),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getDownloadsDirectory, []),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [EpisodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpisodeRepository extends _i1.Mock implements _i10.EpisodeRepository {
  MockEpisodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i11.Episode>> getByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getByPodcastId, [podcastId]),
            returnValue: _i4.Future<List<_i11.Episode>>.value(<_i11.Episode>[]),
          )
          as _i4.Future<List<_i11.Episode>>);

  @override
  _i4.Stream<List<_i11.Episode>> watchByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#watchByPodcastId, [podcastId]),
            returnValue: _i4.Stream<List<_i11.Episode>>.empty(),
          )
          as _i4.Stream<List<_i11.Episode>>);

  @override
  _i4.Future<_i11.Episode?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i11.Episode?>.value(),
          )
          as _i4.Future<_i11.Episode?>);

  @override
  _i4.Future<_i11.Episode?> getByAudioUrl(String? audioUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getByAudioUrl, [audioUrl]),
            returnValue: _i4.Future<_i11.Episode?>.value(),
          )
          as _i4.Future<_i11.Episode?>);

  @override
  _i4.Future<_i11.Episode?> getByPodcastIdAndGuid(
    int? podcastId,
    String? guid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByPodcastIdAndGuid, [podcastId, guid]),
            returnValue: _i4.Future<_i11.Episode?>.value(),
          )
          as _i4.Future<_i11.Episode?>);

  @override
  _i4.Future<void> upsertEpisodes(List<_i11.Episode>? episodes) =>
      (super.noSuchMethod(
            Invocation.method(#upsertEpisodes, [episodes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertFromFeedItems(
    int? podcastId,
    List<_i12.PodcastItem>? items, {
    _i13.NumberingExtractor? extractor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertFromFeedItems,
              [podcastId, items],
              {#extractor: extractor},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertFromFeedItemsWithConfig(
    int? podcastId,
    List<_i12.PodcastItem>? items, {
    required _i14.PresetConfig? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertFromFeedItemsWithConfig,
              [podcastId, items],
              {#config: config},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i11.Episode>> getByIds(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getByIds, [ids]),
            returnValue: _i4.Future<List<_i11.Episode>>.value(<_i11.Episode>[]),
          )
          as _i4.Future<List<_i11.Episode>>);

  @override
  _i4.Future<Set<String>> getGuidsByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getGuidsByPodcastId, [podcastId]),
            returnValue: _i4.Future<Set<String>>.value(<String>{}),
          )
          as _i4.Future<Set<String>>);

  @override
  _i4.Future<_i11.Episode?> getNewestByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getNewestByPodcastId, [podcastId]),
            returnValue: _i4.Future<_i11.Episode?>.value(),
          )
          as _i4.Future<_i11.Episode?>);

  @override
  _i4.Future<void> storeTranscriptAndChapterDataFromParsed(
    int? podcastId,
    List<_i15.ParsedEpisodeMediaMeta>? mediaMetas,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeTranscriptAndChapterDataFromParsed, [
              podcastId,
              mediaMetas,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> deleteByPodcastIdAndGuids(
    int? podcastId,
    Set<String>? guids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteByPodcastIdAndGuids, [podcastId, guids]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i11.Episode>> getPendingAutoDownloadByPodcastId(
    int? podcastId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingAutoDownloadByPodcastId, [podcastId]),
            returnValue: _i4.Future<List<_i11.Episode>>.value(<_i11.Episode>[]),
          )
          as _i4.Future<List<_i11.Episode>>);

  @override
  _i4.Future<void> markAutoDownloadEnqueued(Iterable<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#markAutoDownloadEnqueued, [ids]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i11.Episode>> getSubsequentEpisodes({
    required int? podcastId,
    required int? afterEpisodeNumber,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSubsequentEpisodes, [], {
              #podcastId: podcastId,
              #afterEpisodeNumber: afterEpisodeNumber,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i11.Episode>>.value(<_i11.Episode>[]),
          )
          as _i4.Future<List<_i11.Episode>>);
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i16.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Subscription> subscribe({
    required String? itunesId,
    required String? feedUrl,
    required String? title,
    required String? artistName,
    String? artworkUrl,
    String? description,
    List<String>? genres,
    bool? explicit,
    _i17.SubscribeSource? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {
              #itunesId: itunesId,
              #feedUrl: feedUrl,
              #title: title,
              #artistName: artistName,
              #artworkUrl: artworkUrl,
              #description: description,
              #genres: genres,
              #explicit: explicit,
              #source: source,
            }),
            returnValue: _i4.Future<_i2.Subscription>.value(
              _FakeSubscription_0(
                this,
                Invocation.method(#subscribe, [], {
                  #itunesId: itunesId,
                  #feedUrl: feedUrl,
                  #title: title,
                  #artistName: artistName,
                  #artworkUrl: artworkUrl,
                  #description: description,
                  #genres: genres,
                  #explicit: explicit,
                  #source: source,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Subscription>);

  @override
  _i4.Future<void> unsubscribe(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [itunesId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isSubscribed(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribed, [itunesId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isSubscribedByFeedUrl(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribedByFeedUrl, [feedUrl]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.Subscription>> getSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptions, []),
            returnValue: _i4.Future<List<_i2.Subscription>>.value(
              <_i2.Subscription>[],
            ),
          )
          as _i4.Future<List<_i2.Subscription>>);

  @override
  _i4.Stream<List<_i2.Subscription>> watchSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#watchSubscriptions, []),
            returnValue: _i4.Stream<List<_i2.Subscription>>.empty(),
          )
          as _i4.Stream<List<_i2.Subscription>>);

  @override
  _i4.Future<_i2.Subscription?> getSubscription(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscription, [itunesId]),
            returnValue: _i4.Future<_i2.Subscription?>.value(),
          )
          as _i4.Future<_i2.Subscription?>);

  @override
  _i4.Future<_i2.Subscription?> getByFeedUrl(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getByFeedUrl, [feedUrl]),
            returnValue: _i4.Future<_i2.Subscription?>.value(),
          )
          as _i4.Future<_i2.Subscription?>);

  @override
  _i4.Future<_i2.Subscription?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i2.Subscription?>.value(),
          )
          as _i4.Future<_i2.Subscription?>);

  @override
  _i4.Future<void> updateLastRefreshed(String? itunesId, DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastRefreshed, [itunesId, timestamp]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Subscription> getOrCreateCached({
    required String? itunesId,
    required String? feedUrl,
    required String? title,
    required String? artistName,
    String? artworkUrl,
    String? description,
    List<String>? genres,
    bool? explicit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateCached, [], {
              #itunesId: itunesId,
              #feedUrl: feedUrl,
              #title: title,
              #artistName: artistName,
              #artworkUrl: artworkUrl,
              #description: description,
              #genres: genres,
              #explicit: explicit,
            }),
            returnValue: _i4.Future<_i2.Subscription>.value(
              _FakeSubscription_0(
                this,
                Invocation.method(#getOrCreateCached, [], {
                  #itunesId: itunesId,
                  #feedUrl: feedUrl,
                  #title: title,
                  #artistName: artistName,
                  #artworkUrl: artworkUrl,
                  #description: description,
                  #genres: genres,
                  #explicit: explicit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Subscription>);

  @override
  _i4.Future<_i2.Subscription?> promoteToSubscribed(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#promoteToSubscribed, [itunesId]),
            returnValue: _i4.Future<_i2.Subscription?>.value(),
          )
          as _i4.Future<_i2.Subscription?>);

  @override
  _i4.Future<void> updateLastAccessed(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastAccessed, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Subscription>> getCachedSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSubscriptions, []),
            returnValue: _i4.Future<List<_i2.Subscription>>.value(
              <_i2.Subscription>[],
            ),
          )
          as _i4.Future<List<_i2.Subscription>>);

  @override
  _i4.Future<bool> deleteById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> updateAutoDownload(int? id, {required bool? autoDownload}) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateAutoDownload,
              [id],
              {#autoDownload: autoDownload},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDescription(int? id, String? description) =>
      (super.noSuchMethod(
            Invocation.method(#updateDescription, [id, description]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateHttpCacheHeaders(
    int? id, {
    String? etag,
    String? lastModified,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateHttpCacheHeaders,
              [id],
              {#etag: etag, #lastModified: lastModified},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllHttpCacheHeaders() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllHttpCacheHeaders, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
