// Mocks generated by Mockito 5.4.6 from annotations
// in audiflow_domain/test/features/download/services/download_queue_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:audiflow_domain/src/features/download/models/download_status.dart'
    as _i5;
import 'package:audiflow_domain/src/features/download/models/download_task.dart'
    as _i4;
import 'package:audiflow_domain/src/features/download/repositories/download_repository.dart'
    as _i2;
import 'package:audiflow_domain/src/features/download/services/download_file_service.dart'
    as _i6;
import 'package:audiflow_domain/src/features/feed/models/episode.dart' as _i9;
import 'package:audiflow_domain/src/features/feed/models/feed_parse_progress.dart'
    as _i13;
import 'package:audiflow_domain/src/features/feed/models/numbering_extractor.dart'
    as _i11;
import 'package:audiflow_domain/src/features/feed/models/smart_playlist_pattern_config.dart'
    as _i12;
import 'package:audiflow_domain/src/features/feed/repositories/episode_repository.dart'
    as _i8;
import 'package:audiflow_podcast/audiflow_podcast.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DownloadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadRepository extends _i1.Mock
    implements _i2.DownloadRepository {
  MockDownloadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DownloadTask?> createDownload({
    required int? episodeId,
    required String? audioUrl,
    required bool? wifiOnly,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDownload, [], {
              #episodeId: episodeId,
              #audioUrl: audioUrl,
              #wifiOnly: wifiOnly,
            }),
            returnValue: _i3.Future<_i4.DownloadTask?>.value(),
          )
          as _i3.Future<_i4.DownloadTask?>);

  @override
  _i3.Future<_i4.DownloadTask?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.DownloadTask?>.value(),
          )
          as _i3.Future<_i4.DownloadTask?>);

  @override
  _i3.Future<_i4.DownloadTask?> getByEpisodeId(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getByEpisodeId, [episodeId]),
            returnValue: _i3.Future<_i4.DownloadTask?>.value(),
          )
          as _i3.Future<_i4.DownloadTask?>);

  @override
  _i3.Stream<_i4.DownloadTask?> watchByEpisodeId(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#watchByEpisodeId, [episodeId]),
            returnValue: _i3.Stream<_i4.DownloadTask?>.empty(),
          )
          as _i3.Stream<_i4.DownloadTask?>);

  @override
  _i3.Future<List<_i4.DownloadTask>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i4.DownloadTask>>.value(
              <_i4.DownloadTask>[],
            ),
          )
          as _i3.Future<List<_i4.DownloadTask>>);

  @override
  _i3.Stream<List<_i4.DownloadTask>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i4.DownloadTask>>.empty(),
          )
          as _i3.Stream<List<_i4.DownloadTask>>);

  @override
  _i3.Future<List<_i4.DownloadTask>> getByStatus(_i5.DownloadStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getByStatus, [status]),
            returnValue: _i3.Future<List<_i4.DownloadTask>>.value(
              <_i4.DownloadTask>[],
            ),
          )
          as _i3.Future<List<_i4.DownloadTask>>);

  @override
  _i3.Stream<List<_i4.DownloadTask>> watchByStatus(
    _i5.DownloadStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchByStatus, [status]),
            returnValue: _i3.Stream<List<_i4.DownloadTask>>.empty(),
          )
          as _i3.Stream<List<_i4.DownloadTask>>);

  @override
  _i3.Future<_i4.DownloadTask?> getCompletedForEpisode(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedForEpisode, [episodeId]),
            returnValue: _i3.Future<_i4.DownloadTask?>.value(),
          )
          as _i3.Future<_i4.DownloadTask?>);

  @override
  _i3.Future<_i4.DownloadTask?> getNextPending({required bool? isOnWifi}) =>
      (super.noSuchMethod(
            Invocation.method(#getNextPending, [], {#isOnWifi: isOnWifi}),
            returnValue: _i3.Future<_i4.DownloadTask?>.value(),
          )
          as _i3.Future<_i4.DownloadTask?>);

  @override
  _i3.Future<void> updateProgress({
    required int? id,
    required int? downloadedBytes,
    int? totalBytes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgress, [], {
              #id: id,
              #downloadedBytes: downloadedBytes,
              #totalBytes: totalBytes,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateStatus({
    required int? id,
    required _i5.DownloadStatus? status,
    String? localPath,
    String? lastError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [], {
              #id: id,
              #status: status,
              #localPath: localPath,
              #lastError: lastError,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> incrementRetryCount(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRetryCount, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getActiveCount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalStorageUsed() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalStorageUsed, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> deleteAllCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllCompleted, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [DownloadFileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadFileService extends _i1.Mock
    implements _i6.DownloadFileService {
  MockDownloadFileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> downloadFile({
    required int? taskId,
    required String? url,
    required int? episodeId,
    required String? episodeTitle,
    required _i6.DownloadProgressCallback? onProgress,
    int? resumeFromBytes = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [], {
              #taskId: taskId,
              #url: url,
              #episodeId: episodeId,
              #episodeTitle: episodeTitle,
              #onProgress: onProgress,
              #resumeFromBytes: resumeFromBytes,
            }),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#downloadFile, [], {
                  #taskId: taskId,
                  #url: url,
                  #episodeId: episodeId,
                  #episodeTitle: episodeTitle,
                  #onProgress: onProgress,
                  #resumeFromBytes: resumeFromBytes,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  void cancelDownload(int? taskId) => super.noSuchMethod(
    Invocation.method(#cancelDownload, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> deleteFile(String? localPath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [localPath]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getFileSize(String? localPath) =>
      (super.noSuchMethod(
            Invocation.method(#getFileSize, [localPath]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> fileExists(String? localPath) =>
      (super.noSuchMethod(
            Invocation.method(#fileExists, [localPath]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String> getDownloadsDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadsDirectory, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getDownloadsDirectory, []),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [EpisodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpisodeRepository extends _i1.Mock implements _i8.EpisodeRepository {
  MockEpisodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i9.Episode>> getByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getByPodcastId, [podcastId]),
            returnValue: _i3.Future<List<_i9.Episode>>.value(<_i9.Episode>[]),
          )
          as _i3.Future<List<_i9.Episode>>);

  @override
  _i3.Stream<List<_i9.Episode>> watchByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#watchByPodcastId, [podcastId]),
            returnValue: _i3.Stream<List<_i9.Episode>>.empty(),
          )
          as _i3.Stream<List<_i9.Episode>>);

  @override
  _i3.Future<_i9.Episode?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i9.Episode?>.value(),
          )
          as _i3.Future<_i9.Episode?>);

  @override
  _i3.Future<_i9.Episode?> getByAudioUrl(String? audioUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getByAudioUrl, [audioUrl]),
            returnValue: _i3.Future<_i9.Episode?>.value(),
          )
          as _i3.Future<_i9.Episode?>);

  @override
  _i3.Future<_i9.Episode?> getByPodcastIdAndGuid(
    int? podcastId,
    String? guid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getByPodcastIdAndGuid, [podcastId, guid]),
            returnValue: _i3.Future<_i9.Episode?>.value(),
          )
          as _i3.Future<_i9.Episode?>);

  @override
  _i3.Future<void> upsertEpisodes(List<_i9.Episode>? episodes) =>
      (super.noSuchMethod(
            Invocation.method(#upsertEpisodes, [episodes]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertFromFeedItems(
    int? podcastId,
    List<_i10.PodcastItem>? items, {
    _i11.NumberingExtractor? extractor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertFromFeedItems,
              [podcastId, items],
              {#extractor: extractor},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> upsertFromFeedItemsWithConfig(
    int? podcastId,
    List<_i10.PodcastItem>? items, {
    required _i12.SmartPlaylistPatternConfig? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertFromFeedItemsWithConfig,
              [podcastId, items],
              {#config: config},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.Episode>> getByIds(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getByIds, [ids]),
            returnValue: _i3.Future<List<_i9.Episode>>.value(<_i9.Episode>[]),
          )
          as _i3.Future<List<_i9.Episode>>);

  @override
  _i3.Future<Set<String>> getGuidsByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getGuidsByPodcastId, [podcastId]),
            returnValue: _i3.Future<Set<String>>.value(<String>{}),
          )
          as _i3.Future<Set<String>>);

  @override
  _i3.Future<_i9.Episode?> getNewestByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getNewestByPodcastId, [podcastId]),
            returnValue: _i3.Future<_i9.Episode?>.value(),
          )
          as _i3.Future<_i9.Episode?>);

  @override
  _i3.Future<void> storeTranscriptAndChapterDataFromParsed(
    int? podcastId,
    List<_i13.ParsedEpisodeMediaMeta>? mediaMetas,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#storeTranscriptAndChapterDataFromParsed, [
              podcastId,
              mediaMetas,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> deleteByPodcastIdAndGuids(
    int? podcastId,
    Set<String>? guids, {
    Set<String>? protectedGuids = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteByPodcastIdAndGuids,
              [podcastId, guids],
              {#protectedGuids: protectedGuids},
            ),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i9.Episode>> getSubsequentEpisodes({
    required int? podcastId,
    required int? afterEpisodeNumber,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSubsequentEpisodes, [], {
              #podcastId: podcastId,
              #afterEpisodeNumber: afterEpisodeNumber,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i9.Episode>>.value(<_i9.Episode>[]),
          )
          as _i3.Future<List<_i9.Episode>>);
}
