import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")
}

val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

android {
    namespace = "com.reedom.audiflow_app"
    // permission_handler_android 14.x compiles against SDK 37, which is
    // above the Flutter 3.47 default (36). Keep in sync with that plugin.
    compileSdk = 37
    ndkVersion = flutter.ndkVersion

    // AGP 9 disables resValue by default; flavorizr.gradle.kts uses it for
    // the per-flavor app_name.
    buildFeatures {
        resValues = true
    }

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId = "com.reedom.audiflow_app"
        minSdk = 26
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    // Dev builds report the highest stg tag's version: the pubspec version
    // lags on main because only the release workflows rewrite it. The
    // flavors are created later by flavorizr.gradle.kts, hence configureEach.
    val devVersion = providers.exec {
        commandLine("bash", rootProject.file("../../../tools/dev-version.sh").path)
        isIgnoreExitValue = true
    }.standardOutput.asText.get().trim().split(" ")
    productFlavors.configureEach {
        if (name == "dev" && devVersion.size == 2) {
            versionName = devVersion[0]
            versionCode = devVersion[1].toInt()
        }
    }

    if (keystorePropertiesFile.exists()) {
        signingConfigs {
            create("release") {
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
                storeFile = file(keystoreProperties["storeFile"] as String)
                storePassword = keystoreProperties["storePassword"] as String
            }
        }
    }

    buildTypes {
        release {
            if (keystorePropertiesFile.exists()) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
    }
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")
    // SystemOutputSwitcherDialogController opens the system output picker.
    implementation("androidx.mediarouter:mediarouter:1.8.1")
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----
