/// Base class for all all client-side errors that can be generated by the app
sealed class AppException implements Exception {
  const AppException(this.code, this.message);

  final String code;
  final String message;

  @override
  String toString() => message;
}

class UnknownException extends AppException {
  const UnknownException({String message = 'Unknown error occurred'})
      : super('unknown', message);
}

class NotFoundException extends AppException {
  const NotFoundException({String message = 'Not found'})
      : super('notFound', message);
}

class ArgumentErrorException extends AppException {
  const ArgumentErrorException({String message = 'Invalid argument'})
      : super('argumentError', message);
}

sealed class NetworkException extends AppException {
  const NetworkException(super.code, super.message);
}

class NoConnectivityException extends NetworkException {
  const NoConnectivityException() : super('noConnectivity', 'No connectivity');
}

class NetworkTimeoutException extends NetworkException {
  const NetworkTimeoutException({
    String message = 'Network timeout error occurred',
  }) : super('timeout', message);
}

sealed class HttpException extends NetworkException {
  HttpException(super.code, super.message);

  factory HttpException.fromStatusCode(int? statusCode) {
    if (statusCode == null) {
      return UnknownNetworkException('statusCode is null');
    }

    return switch (statusCode) {
      >= 400 && < 500 => ClientNetworkException(
          'Client error occurred($statusCode)',
        ),
      >= 500 && < 600 => ServerNetworkException(
          'Server error occurred($statusCode)',
        ),
      _ => throw ArgumentErrorException(
          message: 'Invalid status code: $statusCode.',
        ),
    };
  }
}

class ClientNetworkException extends HttpException {
  ClientNetworkException(String message) : super('clientError', message);
}

class ServerNetworkException extends HttpException {
  ServerNetworkException(String message) : super('serverError', message);
}

class UnknownNetworkException extends HttpException {
  UnknownNetworkException(String message) : super('networkUnknown', message);
}
