name: audiflow_cli
description: CLI tools for debugging Audiflow features
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  audiflow_domain:
    path: ../audiflow_domain
  audiflow_podcast:
    path: ../audiflow_podcast
  args: ^2.6.0
  http: ^1.3.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
