// Mocks generated by Mockito 5.4.6 from annotations
// in audiflow_domain/test/features/player/services/playback_history_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:audiflow_domain/src/common/database/app_database.dart' as _i4;
import 'package:audiflow_domain/src/features/player/repositories/playback_history_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PlaybackHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaybackHistoryRepository extends _i1.Mock
    implements _i2.PlaybackHistoryRepository {
  MockPlaybackHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.PlaybackHistory?> getByEpisodeId(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getByEpisodeId, [episodeId]),
            returnValue: _i3.Future<_i4.PlaybackHistory?>.value(),
          )
          as _i3.Future<_i4.PlaybackHistory?>);

  @override
  _i3.Future<void> saveProgress({
    required int? episodeId,
    required int? positionMs,
    int? durationMs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgress, [], {
              #episodeId: episodeId,
              #positionMs: positionMs,
              #durationMs: durationMs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markCompleted(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#markCompleted, [episodeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markIncomplete(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#markIncomplete, [episodeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> incrementPlayCount(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementPlayCount, [episodeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isCompleted(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#isCompleted, [episodeId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<double?> getProgressPercent(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressPercent, [episodeId]),
            returnValue: _i3.Future<double?>.value(),
          )
          as _i3.Future<double?>);

  @override
  _i3.Stream<List<_i4.PlaybackHistory>> watchInProgress({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#watchInProgress, [], {#limit: limit}),
            returnValue: _i3.Stream<List<_i4.PlaybackHistory>>.empty(),
          )
          as _i3.Stream<List<_i4.PlaybackHistory>>);
}
