// Mocks generated by Mockito 5.4.6 from annotations
// in audiflow_domain/test/features/player/services/playback_history_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:audiflow_domain/src/features/download/models/download_task.dart'
    as _i6;
import 'package:audiflow_domain/src/features/download/services/download_service.dart'
    as _i5;
import 'package:audiflow_domain/src/features/player/models/playback_history.dart'
    as _i4;
import 'package:audiflow_domain/src/features/player/repositories/playback_history_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PlaybackHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaybackHistoryRepository extends _i1.Mock
    implements _i2.PlaybackHistoryRepository {
  MockPlaybackHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.PlaybackHistory?> getByEpisodeId(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getByEpisodeId, [episodeId]),
            returnValue: _i3.Future<_i4.PlaybackHistory?>.value(),
          )
          as _i3.Future<_i4.PlaybackHistory?>);

  @override
  _i3.Future<void> saveProgress({
    required int? episodeId,
    required int? positionMs,
    int? durationMs,
    int? listenedDeltaMs = 0,
    int? realtimeDeltaMs = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgress, [], {
              #episodeId: episodeId,
              #positionMs: positionMs,
              #durationMs: durationMs,
              #listenedDeltaMs: listenedDeltaMs,
              #realtimeDeltaMs: realtimeDeltaMs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markCompleted(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#markCompleted, [episodeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markIncomplete(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#markIncomplete, [episodeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> incrementPlayCount(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementPlayCount, [episodeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isCompleted(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#isCompleted, [episodeId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<double?> getProgressPercent(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressPercent, [episodeId]),
            returnValue: _i3.Future<double?>.value(),
          )
          as _i3.Future<double?>);

  @override
  _i3.Future<_i4.PlaybackHistory?> getLastPlayed() =>
      (super.noSuchMethod(
            Invocation.method(#getLastPlayed, []),
            returnValue: _i3.Future<_i4.PlaybackHistory?>.value(),
          )
          as _i3.Future<_i4.PlaybackHistory?>);

  @override
  _i3.Stream<List<_i4.PlaybackHistory>> watchInProgress({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#watchInProgress, [], {#limit: limit}),
            returnValue: _i3.Stream<List<_i4.PlaybackHistory>>.empty(),
          )
          as _i3.Stream<List<_i4.PlaybackHistory>>);

  @override
  _i3.Future<Map<int, _i4.PlaybackHistory>> getByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getByPodcastId, [podcastId]),
            returnValue: _i3.Future<Map<int, _i4.PlaybackHistory>>.value(
              <int, _i4.PlaybackHistory>{},
            ),
          )
          as _i3.Future<Map<int, _i4.PlaybackHistory>>);
}

/// A class which mocks [DownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadService extends _i1.Mock implements _i5.DownloadService {
  MockDownloadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i6.DownloadTask?> get activeDownloadStream =>
      (super.noSuchMethod(
            Invocation.getter(#activeDownloadStream),
            returnValue: _i3.Stream<_i6.DownloadTask?>.empty(),
          )
          as _i3.Stream<_i6.DownloadTask?>);

  @override
  _i3.Future<_i6.DownloadTask?> downloadEpisode(
    int? episodeId, {
    bool? wifiOnly,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadEpisode,
              [episodeId],
              {#wifiOnly: wifiOnly},
            ),
            returnValue: _i3.Future<_i6.DownloadTask?>.value(),
          )
          as _i3.Future<_i6.DownloadTask?>);

  @override
  _i3.Future<int> downloadSeason(
    int? podcastId,
    int? seasonNumber, {
    bool? wifiOnly,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadSeason,
              [podcastId, seasonNumber],
              {#wifiOnly: wifiOnly},
            ),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> downloadEpisodes(List<int>? episodeIds, {bool? wifiOnly}) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadEpisodes,
              [episodeIds],
              {#wifiOnly: wifiOnly},
            ),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> cancelEpisodeDownloads(List<int>? episodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#cancelEpisodeDownloads, [episodeIds]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> resumeEpisodeDownloads(List<int>? episodeIds) =>
      (super.noSuchMethod(
            Invocation.method(#resumeEpisodeDownloads, [episodeIds]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> pause(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#pause, [taskId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resume(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#resume, [taskId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancel(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [taskId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> retry(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#retry, [taskId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [taskId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAllCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllCompleted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getLocalPath(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalPath, [episodeId]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> validateDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#validateDownloads, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> onEpisodeCompleted(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#onEpisodeCompleted, [episodeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getTotalStorageUsed() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalStorageUsed, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
