// Mocks generated by Mockito 5.4.6 from annotations
// in audiflow_domain/test/features/queue/services/queue_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:audiflow_domain/src/common/database/app_database.dart' as _i2;
import 'package:audiflow_domain/src/features/feed/models/smart_playlist_episode_extractor.dart'
    as _i9;
import 'package:audiflow_domain/src/features/feed/repositories/episode_repository.dart'
    as _i7;
import 'package:audiflow_domain/src/features/queue/models/playback_queue.dart'
    as _i5;
import 'package:audiflow_domain/src/features/queue/repositories/queue_repository.dart'
    as _i3;
import 'package:audiflow_podcast/audiflow_podcast.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeQueueItem_0 extends _i1.SmartFake implements _i2.QueueItem {
  _FakeQueueItem_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QueueRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueueRepository extends _i1.Mock implements _i3.QueueRepository {
  MockQueueRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.QueueItem> addToEnd(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#addToEnd, [episodeId]),
            returnValue: _i4.Future<_i2.QueueItem>.value(
              _FakeQueueItem_0(this, Invocation.method(#addToEnd, [episodeId])),
            ),
          )
          as _i4.Future<_i2.QueueItem>);

  @override
  _i4.Future<_i2.QueueItem> addToFront(int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#addToFront, [episodeId]),
            returnValue: _i4.Future<_i2.QueueItem>.value(
              _FakeQueueItem_0(
                this,
                Invocation.method(#addToFront, [episodeId]),
              ),
            ),
          )
          as _i4.Future<_i2.QueueItem>);

  @override
  _i4.Future<void> replaceWithAdhoc({
    required List<int>? episodeIds,
    required String? sourceContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replaceWithAdhoc, [], {
              #episodeIds: episodeIds,
              #sourceContext: sourceContext,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> remove(int? queueItemId) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [queueItemId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFirst() =>
      (super.noSuchMethod(
            Invocation.method(#removeFirst, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reorder(int? queueItemId, int? newIndex) =>
      (super.noSuchMethod(
            Invocation.method(#reorder, [queueItemId, newIndex]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.PlaybackQueue> getQueue() =>
      (super.noSuchMethod(
            Invocation.method(#getQueue, []),
            returnValue: _i4.Future<_i5.PlaybackQueue>.value(
              _i6.dummyValue<_i5.PlaybackQueue>(
                this,
                Invocation.method(#getQueue, []),
              ),
            ),
          )
          as _i4.Future<_i5.PlaybackQueue>);

  @override
  _i4.Stream<_i5.PlaybackQueue> watchQueue() =>
      (super.noSuchMethod(
            Invocation.method(#watchQueue, []),
            returnValue: _i4.Stream<_i5.PlaybackQueue>.empty(),
          )
          as _i4.Stream<_i5.PlaybackQueue>);

  @override
  _i4.Future<bool> hasManualItems() =>
      (super.noSuchMethod(
            Invocation.method(#hasManualItems, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Episode?> getNextEpisode() =>
      (super.noSuchMethod(
            Invocation.method(#getNextEpisode, []),
            returnValue: _i4.Future<_i2.Episode?>.value(),
          )
          as _i4.Future<_i2.Episode?>);
}

/// A class which mocks [EpisodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpisodeRepository extends _i1.Mock implements _i7.EpisodeRepository {
  MockEpisodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Episode>> getByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getByPodcastId, [podcastId]),
            returnValue: _i4.Future<List<_i2.Episode>>.value(<_i2.Episode>[]),
          )
          as _i4.Future<List<_i2.Episode>>);

  @override
  _i4.Stream<List<_i2.Episode>> watchByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#watchByPodcastId, [podcastId]),
            returnValue: _i4.Stream<List<_i2.Episode>>.empty(),
          )
          as _i4.Stream<List<_i2.Episode>>);

  @override
  _i4.Future<_i2.Episode?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i2.Episode?>.value(),
          )
          as _i4.Future<_i2.Episode?>);

  @override
  _i4.Future<_i2.Episode?> getByAudioUrl(String? audioUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getByAudioUrl, [audioUrl]),
            returnValue: _i4.Future<_i2.Episode?>.value(),
          )
          as _i4.Future<_i2.Episode?>);

  @override
  _i4.Future<void> upsertEpisodes(List<_i2.EpisodesCompanion>? episodes) =>
      (super.noSuchMethod(
            Invocation.method(#upsertEpisodes, [episodes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upsertFromFeedItems(
    int? podcastId,
    List<_i8.PodcastItem>? items, {
    _i9.SmartPlaylistEpisodeExtractor? extractor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upsertFromFeedItems,
              [podcastId, items],
              {#extractor: extractor},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Episode>> getByIds(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getByIds, [ids]),
            returnValue: _i4.Future<List<_i2.Episode>>.value(<_i2.Episode>[]),
          )
          as _i4.Future<List<_i2.Episode>>);

  @override
  _i4.Future<Set<String>> getGuidsByPodcastId(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#getGuidsByPodcastId, [podcastId]),
            returnValue: _i4.Future<Set<String>>.value(<String>{}),
          )
          as _i4.Future<Set<String>>);

  @override
  _i4.Future<List<_i2.Episode>> getSubsequentEpisodes({
    required int? podcastId,
    required int? afterEpisodeNumber,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSubsequentEpisodes, [], {
              #podcastId: podcastId,
              #afterEpisodeNumber: afterEpisodeNumber,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.Episode>>.value(<_i2.Episode>[]),
          )
          as _i4.Future<List<_i2.Episode>>);
}
