// Mocks generated by Mockito 5.4.6 from annotations
// in audiflow_domain/test/features/subscription/services/opml_import_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:audiflow_domain/src/features/subscription/models/subscriptions.dart'
    as _i2;
import 'package:audiflow_domain/src/features/subscription/repositories/subscription_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSubscription_0 extends _i1.SmartFake implements _i2.Subscription {
  _FakeSubscription_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i3.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Subscription> subscribe({
    required String? itunesId,
    required String? feedUrl,
    required String? title,
    required String? artistName,
    String? artworkUrl,
    String? description,
    List<String>? genres,
    bool? explicit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {
              #itunesId: itunesId,
              #feedUrl: feedUrl,
              #title: title,
              #artistName: artistName,
              #artworkUrl: artworkUrl,
              #description: description,
              #genres: genres,
              #explicit: explicit,
            }),
            returnValue: _i4.Future<_i2.Subscription>.value(
              _FakeSubscription_0(
                this,
                Invocation.method(#subscribe, [], {
                  #itunesId: itunesId,
                  #feedUrl: feedUrl,
                  #title: title,
                  #artistName: artistName,
                  #artworkUrl: artworkUrl,
                  #description: description,
                  #genres: genres,
                  #explicit: explicit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Subscription>);

  @override
  _i4.Future<void> unsubscribe(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [itunesId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isSubscribed(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribed, [itunesId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isSubscribedByFeedUrl(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribedByFeedUrl, [feedUrl]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i2.Subscription>> getSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptions, []),
            returnValue: _i4.Future<List<_i2.Subscription>>.value(
              <_i2.Subscription>[],
            ),
          )
          as _i4.Future<List<_i2.Subscription>>);

  @override
  _i4.Stream<List<_i2.Subscription>> watchSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#watchSubscriptions, []),
            returnValue: _i4.Stream<List<_i2.Subscription>>.empty(),
          )
          as _i4.Stream<List<_i2.Subscription>>);

  @override
  _i4.Future<_i2.Subscription?> getSubscription(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscription, [itunesId]),
            returnValue: _i4.Future<_i2.Subscription?>.value(),
          )
          as _i4.Future<_i2.Subscription?>);

  @override
  _i4.Future<_i2.Subscription?> getByFeedUrl(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getByFeedUrl, [feedUrl]),
            returnValue: _i4.Future<_i2.Subscription?>.value(),
          )
          as _i4.Future<_i2.Subscription?>);

  @override
  _i4.Future<_i2.Subscription?> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i4.Future<_i2.Subscription?>.value(),
          )
          as _i4.Future<_i2.Subscription?>);

  @override
  _i4.Future<void> updateLastRefreshed(String? itunesId, DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastRefreshed, [itunesId, timestamp]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Subscription> getOrCreateCached({
    required String? itunesId,
    required String? feedUrl,
    required String? title,
    required String? artistName,
    String? artworkUrl,
    String? description,
    List<String>? genres,
    bool? explicit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateCached, [], {
              #itunesId: itunesId,
              #feedUrl: feedUrl,
              #title: title,
              #artistName: artistName,
              #artworkUrl: artworkUrl,
              #description: description,
              #genres: genres,
              #explicit: explicit,
            }),
            returnValue: _i4.Future<_i2.Subscription>.value(
              _FakeSubscription_0(
                this,
                Invocation.method(#getOrCreateCached, [], {
                  #itunesId: itunesId,
                  #feedUrl: feedUrl,
                  #title: title,
                  #artistName: artistName,
                  #artworkUrl: artworkUrl,
                  #description: description,
                  #genres: genres,
                  #explicit: explicit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Subscription>);

  @override
  _i4.Future<_i2.Subscription?> promoteToSubscribed(String? itunesId) =>
      (super.noSuchMethod(
            Invocation.method(#promoteToSubscribed, [itunesId]),
            returnValue: _i4.Future<_i2.Subscription?>.value(),
          )
          as _i4.Future<_i2.Subscription?>);

  @override
  _i4.Future<void> updateLastAccessed(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastAccessed, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Subscription>> getCachedSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSubscriptions, []),
            returnValue: _i4.Future<List<_i2.Subscription>>.value(
              <_i2.Subscription>[],
            ),
          )
          as _i4.Future<List<_i2.Subscription>>);

  @override
  _i4.Future<bool> deleteById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
