// Mocks generated by Mockito 5.4.6 from annotations
// in audiflow_ai/test/services/voice_command_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:audiflow_ai/src/models/ai_response.dart' as _i2;
import 'package:audiflow_ai/src/models/generation_config.dart' as _i5;
import 'package:audiflow_ai/src/services/text_generation_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAiResponse_0 extends _i1.SmartFake implements _i2.AiResponse {
  _FakeAiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TextGenerationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextGenerationService extends _i1.Mock
    implements _i3.TextGenerationService {
  MockTextGenerationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i4.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> initialize({String? systemInstructions}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #systemInstructions: systemInstructions,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AiResponse> generateText({
    required String? prompt,
    _i5.GenerationConfig? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateText, [], {
              #prompt: prompt,
              #config: config,
            }),
            returnValue: _i4.Future<_i2.AiResponse>.value(
              _FakeAiResponse_0(
                this,
                Invocation.method(#generateText, [], {
                  #prompt: prompt,
                  #config: config,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AiResponse>);

  @override
  _i4.Future<String> generateTextSimple({
    required String? prompt,
    int? maxTokens = 500,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateTextSimple, [], {
              #prompt: prompt,
              #maxTokens: maxTokens,
            }),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#generateTextSimple, [], {
                  #prompt: prompt,
                  #maxTokens: maxTokens,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
