// Mocks generated by Mockito 5.4.6 from annotations
// in audiflow_ai/test/audiflow_ai_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:audiflow_ai/src/audiflow_ai.dart' as _i11;
import 'package:audiflow_ai/src/models/ai_response.dart' as _i2;
import 'package:audiflow_ai/src/models/episode_summary.dart' as _i3;
import 'package:audiflow_ai/src/models/generation_config.dart' as _i7;
import 'package:audiflow_ai/src/models/summarization_config.dart' as _i10;
import 'package:audiflow_ai/src/models/voice_command.dart' as _i4;
import 'package:audiflow_ai/src/services/summarization_service.dart' as _i9;
import 'package:audiflow_ai/src/services/text_generation_service.dart' as _i5;
import 'package:audiflow_ai/src/services/voice_command_service.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAiResponse_0 extends _i1.SmartFake implements _i2.AiResponse {
  _FakeAiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEpisodeSummary_1 extends _i1.SmartFake
    implements _i3.EpisodeSummary {
  _FakeEpisodeSummary_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVoiceCommand_2 extends _i1.SmartFake implements _i4.VoiceCommand {
  _FakeVoiceCommand_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TextGenerationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextGenerationService extends _i1.Mock
    implements _i5.TextGenerationService {
  MockTextGenerationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> initialize({String? systemInstructions}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #systemInstructions: systemInstructions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.AiResponse> generateText({
    required String? prompt,
    _i7.GenerationConfig? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateText, [], {
              #prompt: prompt,
              #config: config,
            }),
            returnValue: _i6.Future<_i2.AiResponse>.value(
              _FakeAiResponse_0(
                this,
                Invocation.method(#generateText, [], {
                  #prompt: prompt,
                  #config: config,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.AiResponse>);

  @override
  _i6.Future<String> generateTextSimple({
    required String? prompt,
    int? maxTokens = 500,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateTextSimple, [], {
              #prompt: prompt,
              #maxTokens: maxTokens,
            }),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#generateTextSimple, [], {
                  #prompt: prompt,
                  #maxTokens: maxTokens,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SummarizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSummarizationService extends _i1.Mock
    implements _i9.SummarizationService {
  MockSummarizationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> summarize({
    required String? text,
    required _i10.SummarizationConfig? config,
    _i11.AiProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#summarize, [], {
              #text: text,
              #config: config,
              #onProgress: onProgress,
            }),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#summarize, [], {
                  #text: text,
                  #config: config,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i3.EpisodeSummary> summarizeEpisode({
    required String? title,
    required String? description,
    String? transcript,
    required _i10.SummarizationConfig? config,
    _i11.AiProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#summarizeEpisode, [], {
              #title: title,
              #description: description,
              #transcript: transcript,
              #config: config,
              #onProgress: onProgress,
            }),
            returnValue: _i6.Future<_i3.EpisodeSummary>.value(
              _FakeEpisodeSummary_1(
                this,
                Invocation.method(#summarizeEpisode, [], {
                  #title: title,
                  #description: description,
                  #transcript: transcript,
                  #config: config,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.EpisodeSummary>);
}

/// A class which mocks [VoiceCommandService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceCommandService extends _i1.Mock
    implements _i12.VoiceCommandService {
  MockVoiceCommandService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.VoiceCommand> parseCommand(
    String? transcription, {
    String? settingsSnapshot = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #parseCommand,
              [transcription],
              {#settingsSnapshot: settingsSnapshot},
            ),
            returnValue: _i6.Future<_i4.VoiceCommand>.value(
              _FakeVoiceCommand_2(
                this,
                Invocation.method(
                  #parseCommand,
                  [transcription],
                  {#settingsSnapshot: settingsSnapshot},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.VoiceCommand>);
}
